### ISSUE TITLE
Docker desktop install error, but no error message

### ISSUE THREAD

**Issue by nmcc1212** [milanvarady/Applite#37]
When trying to install docker desktop, it just comes up with error, is there a way to get a more verbose error message, maybe the brew command output?

Edit: image of unhelpful "error"
<img width="374" alt="image" src="https://github.com/milanvarady/Applite/assets/48334675/dd63dae9-1311-4ebd-86d4-53ccf611f738">

**Comment by milanvarady** [comment]
The error message should be logged to `Console.app`. Open the console app, and at the top, press the start button to begin collecting logs. After the error has occurred, pause logging and search for applite and filter for errors and faults.

The brew output will be hidden, because private logging mode is turned on by default. You can follow this [stack exchange answer](https://superuser.com/questions/1532031/how-to-show-private-data-in-macos-unified-log/1532052#1532052) to reveal the actual output. It's a bit tedious to do, but it would help me debug the issue.

**Comment by nmcc1212** [comment]
Hi, it seems the error is due to the fact i have docker (not desktop version) installed

`Error:\^[[0m It seems there is already a Binary at '/usr/local/bin/docker'.`

**Comment by nmcc1212** [comment]
which is odd, as downloading docker desktop from the docker website and running that works just fine
