### ISSUE TITLE
Error: This software does not run on macOS versions older than Ventura

### ISSUE THREAD

**Issue by xjzyy** [milanvarady/Applite#57]
macOS Big Sur 11.1   无法安装，是否考虑兼容一下旧版本系统呢

**Comment by milanvarady** [comment]
Applite only works on macOS Ventura (13) or later. This is because Apple only releases new software features for the latest version of their OS, even though they could clearly work on older systems. This makes it hard for developers because they either have to do a lot of workarounds or drop support for older versions of the OS.
