### ISSUE TITLE
Null app homepage URL will cause Applite crash

### ISSUE THREAD

**Issue by bk1d** [milanvarady/Applite#66]
<img width="998" alt="image" src="https://github.com/milanvarady/Applite/assets/30523768/a503a9f8-78a0-4415-9f45-8d3d27bade9c">

**Comment by milanvarady** [comment]
Thanks for reporting the problem!

The crash is fixed in the new [v1.2.5](https://github.com/milanvarady/Applite/releases/tag/v1.2.5) update. The crash will most likely be resolved once [this pull request](https://github.com/Homebrew/homebrew-cask/pull/174018) is merged, until then you can manually install the new version to fix the problem.
