### ISSUE TITLE
Extend system requirements

### ISSUE THREAD

**Issue by Drovosek01** [milanvarady/Applite#8]
Thank you for a good free app, but what is the reason to use only the latest stable version of macOS to launch applications?
Many users do not use the latest generation of macOS.

Please make this app available at least on macOS Catalina 10.15

**Comment by milanvarady** [comment]
I wanted to at least target Big Sur, but the problem is that Apple doesn't understand the term "backwards compatibility" when it comes to SwiftUI. Every new feature they add to SwiftUI is only for the latest version of macOS. And since SwiftUI is a relatively new UI framework, they add things that are missing or greatly improved from the previous solution.

In conclusion, if I wanted to add extended support, I would have to put a ton of work into workarounds for features that are Ventura only.
